apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    -- Crear la base de datos (si no existe)
    CREATE DATABASE IF NOT EXISTS empresa CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

    -- Usar la base de datos
    USE empresa;

    -- Crear la tabla productos
    CREATE TABLE IF NOT EXISTS productos (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nombre VARCHAR(100) NOT NULL,
        descripcion TEXT,
        precio DECIMAL(10, 2) NOT NULL
    ); 